// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Activity {
    "id": number;
    "name": string;
    "isBreak": boolean;
    "isPreset": boolean;
    "archived": boolean;
}

/**
 * ActivityTotal aggregates time per activity. Seconds instead of
 * time.Duration because it crosses the JSON boundary to the frontend.
 */
export interface ActivityTotal {
    "activity": Activity;
    "seconds": number;
}

/**
 * Boundary marks the moment the tagged activity starts. The segment it opens
 * ends at the next boundary, or at Day.EndedAt for the last one.
 */
export interface Boundary {
    "id": number;
    "dayId": number;
    "at": string;
    "activityId": number;
}

export interface Day {
    "id": number;

    /**
     * local calendar date, YYYY-MM-DD
     */
    "date": string;
    "endedAt": string | null;

    /**
     * ordered by At ascending
     */
    "boundaries": Boundary[] | null;
}

export interface DaySummary {
    "dayId": number;
    "date": string;
    "start": string;
    "end": string | null;
    "totalSecs": number;
    "breakSecs": number;
    "workSecs": number;
    "byActivity": ActivityTotal[] | null;
    "segments": Segment[] | null;
}

/**
 * RangeSummary aggregates several days (e.g. a week).
 */
export interface RangeSummary {
    "from": string;
    "to": string;
    "days": DaySummary[] | null;
    "totalSecs": number;
    "breakSecs": number;
    "workSecs": number;
    "byActivity": ActivityTotal[] | null;
}

/**
 * Segment is a derived view: the span between a boundary and its successor.
 */
export interface Segment {
    "boundaryId": number;
    "activity": Activity;
    "start": string;

    /**
     * nil while this segment is still running
     */
    "end": string | null;
}
