// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tracker$0 from "./internal/tracker/models.js";

/**
 * DayView is what the frontend renders: the raw day (boundaries carry the
 * ids needed for edits) plus the derived summary (segments and totals).
 */
export interface DayView {
    "day": tracker$0.Day;
    "summary": tracker$0.DaySummary;
}

/**
 * HomeState is everything the main and quick windows need on load.
 */
export interface HomeState {
    /**
     * local date YYYY-MM-DD
     */
    "today": string;
    "openDay": DayView | null;

    /**
     * may be the same day as OpenDay, or an ended day
     */
    "todayDay": DayView | null;
    "activities": tracker$0.Activity[] | null;
    "defaultActivity": string;
    "breakMinutes": number;
}
