// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TrackerService is the Wails-bound facade over the domain layer. It does
 * edge conversion only: ISO timestamp strings <-> time.Time, local calendar
 * dates, and change events. All rules live in internal/tracker.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tracker$0 from "./internal/tracker/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Activities lists selectable activities for autocomplete and presets.
 */
export function Activities(includeArchived: boolean): $CancellablePromise<tracker$0.Activity[] | null> {
    return $Call.ByID(2746345024, includeArchived);
}

export function AddBoundary(dayID: number, atISO: string, activityName: string): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(2493269170, dayID, atISO, activityName);
}

/**
 * BackFromBreak books the last 45 minutes of the open day as Break and
 * resumes the previous activity now.
 */
export function BackFromBreak(): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(3725487781);
}

/**
 * CreateActivity adds (or revives) an activity without switching to it.
 */
export function CreateActivity(name: string): $CancellablePromise<tracker$0.Activity> {
    return $Call.ByID(4075938780, name);
}

/**
 * DayByDate returns the day for a local date, or null if none exists.
 */
export function DayByDate(date: string): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(3802327488, date);
}

export function DeleteBoundary(boundaryID: number): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(3637532536, boundaryID);
}

export function DeleteDay(dayID: number): $CancellablePromise<void> {
    return $Call.ByID(2764557184, dayID);
}

/**
 * EndDay closes the open day at the given time.
 */
export function EndDay(atISO: string): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(3546203504, atISO);
}

/**
 * ExportCSV writes one row per segment for all days in [from, to] to a
 * location chosen via the native save dialog. Returns the written path, or
 * "" if the user cancelled.
 */
export function ExportCSV($from: string, to: string): $CancellablePromise<string> {
    return $Call.ByID(2806125669, $from, to);
}

export function HomeState(): $CancellablePromise<$models.HomeState> {
    return $Call.ByID(3090852555);
}

/**
 * ListDays returns day rows (without boundaries) in [from, to], newest first.
 */
export function ListDays($from: string, to: string): $CancellablePromise<tracker$0.Day[] | null> {
    return $Call.ByID(3981171014, $from, to);
}

export function MoveBoundary(boundaryID: number, atISO: string): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(1047775298, boundaryID, atISO);
}

/**
 * RangeSummary aggregates the days in [from, to], e.g. a week.
 */
export function RangeSummary($from: string, to: string): $CancellablePromise<tracker$0.RangeSummary> {
    return $Call.ByID(3113250678, $from, to);
}

/**
 * ReopenDay clears a day's end so tracking continues.
 */
export function ReopenDay(dayID: number): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(633205146, dayID);
}

export function SetActivityArchived(id: number, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(13476996, id, archived);
}

/**
 * SetActivityPreset pins/unpins an activity as a one-click button.
 */
export function SetActivityPreset(id: number, preset: boolean): $CancellablePromise<void> {
    return $Call.ByID(1178227401, id, preset);
}

export function SetBoundaryActivity(boundaryID: number, activityName: string): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(2528286596, boundaryID, activityName);
}

/**
 * SetDayEnd edits the end time of an ended day.
 */
export function SetDayEnd(dayID: number, atISO: string): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(521982308, dayID, atISO);
}

export function SetDefaultActivity(name: string): $CancellablePromise<void> {
    return $Call.ByID(651590529, name);
}

/**
 * StartDay starts the day whose local date contains atISO.
 */
export function StartDay(atISO: string, activityName: string): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(325623171, atISO, activityName);
}

/**
 * SwitchActivity records that the given activity starts now on the open day.
 * Unknown names create a new activity (free-text input).
 */
export function SwitchActivity(activityName: string): $CancellablePromise<$models.DayView | null> {
    return $Call.ByID(3453786840, activityName);
}
